import { StringObject } from '@/types/Ui';

export const ranks: string[] = ['X', 'S', 'A', 'B', 'C', 'D', 'E', 'F', 'G'];
export const families: string[] = [
	'Slime',
	'Beast',
	'Dragon',
	'Nature',
	'Material',
	'Demon',
	'Undead',
	'???',
];
export const familiesIcons: StringObject = {
	Slime: 'Slime.png',
	Beast: 'Beast.png',
	Dragon: 'Dragon.png',
	Nature: 'Nature.png',
	// Plant: 'Nature.png',
	Material: 'Material.png',
	Demon: 'Demon.png',
	Undead: 'Undead.png',
	'???': 'Unknown.png',
	Aquatic: 'Aquatic.png',
	Reptile: 'Reptile.png',
	Dinosaur: 'Dinosaur.png',
	Food: 'Food.png',
	Dark: 'Dark.png',
};
// famillies can be in subfamilies
export const subfamilies: string[] = [
	...families,
	'Machine',
	'Elemental',
	'Plant',
	'Aquatic',
	'Bug',
	'Bird',
	'Humanoid',
	'Dragon',
	'Reptile',
	'Amphibian',
	'Fairy',
	'Character',
	'Wizard',
	'Warrior',
	'Food',
	'Ice',
	'Fire',
	'Metal',
	'Gold',
	'Dark',
	'Myth',
	'Space',
	'Jewel',
	'King',
	// 'Music',
	// 'bat',
	// 'golem',
];
